### PR TITLE
Bump version, fix compability issues

### PR DESCRIPTION
**Pull request by SpamixOfficial**
Here's what I've done:

- Bumped the version number
- Updated dependencies
- Fixed compability issues

// Spamix

### CODE REVIEW

**Comment by SpamixOfficial** [comment]
Just tested live on a rp2040 board, works perfectly!

**Review by ithinuel — APPROVED** [review]

**Comment by SpamixOfficial** [comment]
Hello! 

Any idea when this will get merged? If it's in a couple of days then I'll just wait with development but if it's longer than that I'll probably have to reference my git repo in my Cargo.toml.

By the way thanks for this crate, it's amazing :-)

**Comment by ithinuel** [comment]
I merged it but i'm unable to publish a new version yet (my computer is still in a box).

**Comment by SpamixOfficial** [comment]
> I merged it but i'm unable to publish a new version yet (my computer is still in a box).

Haha okay! Thanks for merging, very appreciated! 

Have a great evening/whatever time it is for you :-) 

I'll get back to watching Eurovision now so if you need to reach me please ping me directly!

**Pull request merged**
